# Generated by Django 4.2.6 on 2023-11-10 15:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("code", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("scheme", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PaperSetter",
            fields=[
                ("psid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Request Pending", "Request Pending"),
                            ("In Progress", "In Progress"),
                            ("Update Requested", "Update Requested"),
                            ("Completed", "Completed"),
                        ],
                        default="Request Pending",
                        max_length=20,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.course"
                    ),
                ),
                (
                    "paper_setter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.papersetter",
                    ),
                ),
            ],
        ),
    ]
