# Generated by Django 5.0 on 2024-03-09 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheme",
            name="degree",
            field=models.ForeignKey(
                default="BE",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.degree",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="scheme",
            unique_together={("degree", "year")},
        ),
    ]
