# Generated by Django 5.0 on 2024-02-02 16:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_teacheryear_delete_suggestedpapersetter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacheryear",
            options={"verbose_name_plural": "Teacher-Year Mapping"},
        ),
        migrations.AlterUniqueTogether(
            name="assignment",
            unique_together={("exam", "course")},
        ),
    ]
