# Generated by Django 5.0 on 2024-02-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_teacheryear_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Request Pending", "Request Pending"),
                    ("Invite Rejected", "Invite Rejected"),
                    ("In Progress", "In Progress"),
                    ("Update Requested", "Update Requested"),
                    ("Completed", "Completed"),
                ],
                default="Request Pending",
                max_length=20,
            ),
        ),
    ]
