# Generated by Django 5.0 on 2024-03-14 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_teacherdepartment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="examination",
            unique_together={
                ("degree", "sem", "scheme", "is_supplementary", "is_exam_completed")
            },
        ),
    ]
