# Generated by Django 5.0 on 2024-05-08 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_examination_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.course"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.teacher"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Teacher-Department Mapping",
            },
        ),
        migrations.DeleteModel(
            name="TeacherDepartment",
        ),
    ]
