# Generated by Django 5.0 on 2024-02-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_assignment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="tracking_token",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
