# Generated by Django 5.0 on 2024-02-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_assignment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="comments",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
